### ISSUE TITLE
Not working with pytest-xdist

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/pytest-restrict#191]
Seeing this traceback, with `--restrict-types` in `pytest.ini`:

```
$ pytest
============================================================================================= test session starts ==============================================================================================
platform darwin -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
Using --randomly-seed=1611174015
django: settings: project.settings (from ini)
rootdir: /.../project, configfile: pytest.ini
plugins: requests-mock-1.8.0, randomly-3.4.1, env-0.6.2, django-3.10.0, restrict-3.1.0, xdist-2.1.0, cov-2.10.1, forked-1.3.0
gw0 [478] / gw1 [478] / gw2 [478] / gw3 [478]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/_pytest/main.py", line 257, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/_pytest/main.py", line 313, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/xdist/dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/xdist/dsession.py", line 238, in worker_collectionfinish
INTERNALERROR>     self.sched.schedule()
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/xdist/scheduler/loadscope.py", line 371, in schedule
INTERNALERROR>     self._assign_work_unit(node)
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/xdist/scheduler/loadscope.py", line 265, in _assign_work_unit
INTERNALERROR>     node.send_runtest_some(nodeids_indexes)
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/xdist/workermanage.py", line 283, in send_runtest_some
INTERNALERROR>     self.sendcommand("runtests", indices=indices)
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/xdist/workermanage.py", line 299, in sendcommand
INTERNALERROR>     self.channel.send((name, kwargs))
INTERNALERROR>   File "/.../project/venv/lib/python3.8/site-packages/execnet/gateway_base.py", line 728, in send
INTERNALERROR>     raise IOError("cannot send to {!r}".format(self))
INTERNALERROR> OSError: cannot send to <Channel id=1 closed>

============================================================================================= 23 warnings in 7.29s =============================================================================================
```

The error appears normally with `-n 0`. This is possibly a bug in the latest xdist.

**Comment by adamchainz** [comment]
It seems to happen the same on pytest-xdist < 2 - maybe it's a new pytest thing
